language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
after_success:
  - yarn run bundle
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
